export const tournaments = {
  FETCH_GET_TOURNAMENTS_REQUEST: 'FETCH_GET_TOURNAMENTS_REQUEST',
  FETCH_GET_TOURNAMENTS_SUCCESS: 'FETCH_GET_TOURNAMENTS_SUCCESS',
  FETCH_GET_TOURNAMENTS_FAILURE: 'FETCH_GET_TOURNAMENTS_FAILURE',
};
export const auth = {
  FETCH_LOGIN_REQUEST: 'FETCH_LOGIN_REQUEST',
  FETCH_LOGIN_SUCCESS: 'FETCH_LOGIN_SUCCESS',
  FETCH_LOGIN_FAILURE: 'FETCH_LOGIN_FAILURE',
};

export const newsType = {
  FETCH_CREATE_NEW_REQUEST: 'FETCH_CREATE_NEW_REQUEST',
  FETCH_CREATE_NEW_SUCCESS: 'FETCH_CREATE_NEW_SUCCESS',
  FETCH_CREATE_NEW_FAILURE: 'FETCH_CREATE_NEW_FAILURE',

  FETCH_NEWS_REQUEST: 'FETCH_NEWS_REQUEST',
  FETCH_NEWS_SUCCESS: 'FETCH_NEWS_SUCCESS',
  FETCH_NEWS_FAILURE: 'FETCH_NEWS_FAILURE',

  FETCH_DELETE_NEW_REQUEST: 'FETCH_DELETE_NEW_REQUEST',
  FETCH_DELETE_NEW_SUCCESS: 'FETCH_DELETE_NEW_SUCCESS',
  FETCH_DELETE_NEW_FAILURE: 'FETCH_DELETE_NEW_FAILURE',
};

export const videosType = {
  FETCH_CREATE_VIDEO_REQUEST: 'FETCH_CREATE_VIDEO_REQUEST',
  FETCH_CREATE_VIDEO_SUCCESS: 'FETCH_CREATE_VIDEO_SUCCESS',
  FETCH_CREATE_VIDEO_FAILURE: 'FETCH_CREATE_VIDEO_FAILURE',
};

export const clubsType = {
  FETCH_CREATE_CLUB_REQUEST: 'FETCH_CREATE_CLUB_REQUEST',
  FETCH_CREATE_CLUB_SUCCESS: 'FETCH_CREATE_CLUB_SUCCESS',
  FETCH_CREATE_CLUB_FAILURE: 'FETCH_CREATE_CLUB_FAILURE',
  FETCH_CLUBS_REQUEST: 'FETCH_CLUBS_REQUEST',
  FETCH_CLUBS_SUCCESS: 'FETCH_CLUBS_SUCCESS',
  FETCH_CLUBS_FAILURE: 'FETCH_CLUBS_FAILURE',
};
